server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
